### ISSUE TITLE
"where + and" query performance changes depending on representation

### ISSUE THREAD

**Issue by buchanae** [bmeg/arachne#107]
1. `list(O.query().V().where(aql.eq("_label", "CNASegment")).where(aql.eq("referenceName", "8")).count())`

2. `list(O.query().V().where(aql.and_(aql.eq("_label", "CNASegment"), aql.eq("referenceName", "8"))).count())`

The first one returns in 1 minutes. The second returns in 14 minutes. The "count" stays the same.

**Comment by adamstruck** [comment]
#109 will address this issue for arachne instances backed by mongodb
