### ISSUE TITLE
Tried to follow README, got error. Also, how to turn on server?

### ISSUE THREAD

**Issue by prismofeverything** [bmeg/arachne#2]
This line

    python src/github.com/bmeg/arachne/test/test_amazon_load.py amazon-meta.txt.gz  http://localhost:8000

I believe the second argument needs to be something about the output file, not a host. At least, that is how I got it to work.

Also, could not complete the test as the line

    Turn on local arachne server

does not elaborate as to how this is done. I assume a `go run` of one of these files??

**Comment by kellrott** [comment]
Updated readme
