### ISSUE TITLE
Bundle a small example graph

### ISSUE THREAD

**Issue by buchanae** [bmeg/arachne#22]
New users could get started with queries very quickly if a small example graph was embedded in arachne. The website docs could use this example graph to demonstrate all queries and functionality.

**Comment by kellrott** [comment]
Added in https://github.com/bmeg/arachne/commit/ab518f8e9c665084f04c4ce4d831bd1ff68b102f

**Comment by buchanae** [comment]
Arachne might always create this example graph when it starts? Or perhaps add a CLI command for the user to call in order to create this graph?

**Comment by kellrott** [comment]
Added in #29
