### ISSUE TITLE
aql: Go client should return a NotFound error code

### ISSUE THREAD

**Issue by buchanae** [bmeg/arachne#37]
When a vertex/edge/etc isn't found, this should communicated to the caller with a special error type, NotFound

**Comment by buchanae** [comment]
This is related to this error log:
```
ERROR: 2018/02/05 11:33:43 grpc: server failed to encode response:  rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil
```

...I think. I believe this happens when calling GetVertex on a non-existent vertex. This error log should be removed.

**Comment by kellrott** [comment]
Needs conformance test.

**Comment by adamstruck** [comment]
Added conformance test in 3d1e11c
