### ISSUE TITLE
cmd/get: add commands for GetVertex, GetEdge, etc.

### ISSUE THREAD

**Issue by buchanae** [bmeg/arachne#44]
Having commands like this makes development a lot easier, and allows users to quickly experiment.

@adamstruck I regret not going with <verb> <noun> in funnel. What do you think? Should arachne stick with `arachne vertex get` or `arachne get vertex`

**Comment by kellrott** [comment]
How about just `arachne vertex`?

**Comment by buchanae** [comment]
Also a decent option, although it could be limiting if you want an additional vertex-related command in the future.

**Comment by adamstruck** [comment]
my vote would be for `arachne vertex get`.  This seems to be the pattern I see most often.

**Comment by adamstruck** [comment]
I am fine with scratching the original `arachne vertex get` like commands in favor of the more flexible  query interface. 

It looks as though the javascript code ported from ophion is a bit stale and needs to be updated to match the python aql client.
