### ISSUE TITLE
aql/python: don't hide the expense of first()

### ISSUE THREAD

**Issue by buchanae** [bmeg/arachne#56]
https://github.com/bmeg/arachne/blob/73cab57bd0205828120f3743fe44d3ac80672bb1/aql.py#L311

first() is hiding a potentially large and expensive query + response + marshal/unmarshal. Use limit() to actually get only one element?

**Comment by kellrott** [comment]
Is this still something we should work on?

**Comment by adamstruck** [comment]
There is a `limit` method so I think I am going to just remove `first`
